name: UFW CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Bats
      run: sudo apt-get install bats

    - name: Run tests
      run: sudo bats tests/ufw-setup-test.sh
